#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

brew=$(type -P brew) || exit 0

if [[ ! $MACHTYPE =~ ^(arm|aarch)64- ]] &&
    [[ ! -e /opt/homebrew ]] &&
    [[ $(sysctl -n sysctl.proc_translated 2>/dev/null) != 1 ]]; then
    echo " -> Creating symbolic link: /opt/homebrew -> /usr/local"
    maybe sudo ln -s /usr/local /opt/homebrew
fi

if brewfile=$(find_first Brewfile) ||
    brewfile=$(find_first Brewfile-arm64); then
    # Don't install the Microsoft Defender shim
    maybe defaults write com.microsoft.office InstallDefender -bool false
    maybe brew bundle install --file "$brewfile" --no-upgrade
fi

if ! brewfile=$(find_first Brewfile-x86_64) ||
    [[ $brew != /opt/homebrew/bin/brew ]] ||
    [[ ! -x /usr/local/bin/brew ]]; then
    exit
fi

PATH=$(printf '%s:' "$PATH" |
    awk -vRS=':' '
/^\/opt\/homebrew(\/|$)/ { next } ! i++ { printf "%s", $0; next } { printf ":%s", $0 }')

maybe arch -x86_64 /usr/local/bin/brew bundle install --file "$brewfile" --no-upgrade
