#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

workgroup=LINAC

# Set host name and workgroup if not already set
if ! scutil --get HostName &>/dev/null &&
    h=$(hostname -s | grep .); then
    echo " -> Setting host name: $h"
    for pref in ComputerName LocalHostName HostName; do
        maybe sudo scutil --set "$pref" "$h"
    done
    plist=/Library/Preferences/SystemConfiguration/com.apple.smb.server
    maybe sudo defaults write "$plist" NetBIOSName "$h"
    if ! wg=$(defaults read "$plist" Workgroup 2>/dev/null) ||
        [[ $wg != "$workgroup" ]]; then
        echo " -> Setting workgroup: $workgroup"
        maybe sudo defaults write "$plist" Workgroup "$workgroup"
    fi
fi

# Prevent automatic sleeping on power adapter when display is off
maybe sudo pmset -c sleep 0

# Improve behaviour
maybe defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
maybe defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

maybe defaults write NSGlobalDomain com.apple.sound.beep.feedback -bool true
maybe defaults write com.apple.mail NewMessagesSoundName -string ""
maybe defaults write com.apple.mail PlayMailSounds -bool false
maybe defaults write com.apple.MobileSMS PlaySoundsKey -bool false

maybe defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
maybe defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
maybe defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
maybe defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
maybe defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Improve performance
maybe defaults write com.apple.finder DisableAllAnimations -bool true

# Configure Dock
maybe defaults write com.apple.dock autohide -bool true
maybe defaults write com.apple.dock autohide-delay -float 0
maybe defaults write com.apple.dock launchanim -bool false
maybe defaults write com.apple.dock mineffect -string scale
maybe defaults write com.apple.dock minimize-to-application -bool true
maybe defaults write com.apple.dock show-recents -bool false
maybe defaults write com.apple.dock tilesize -int 60
maybe defaults write com.apple.dock size-immutable -bool true

# Top-right Hot Corner = Start Screen Saver
maybe defaults write com.apple.dock wvous-tr-corner -int 5
maybe defaults write com.apple.dock wvous-tr-modifier -int 0

maybe defaults write NSGlobalDomain AppleSpacesSwitchOnActivate -bool false
#maybe defaults write com.apple.chronod remoteWidgetsEnabled -bool false # Disable iPhone Widgets
#maybe defaults write com.apple.chronod effectiveRemoteWidgetsEnabled -bool false
maybe defaults write com.apple.dock expose-group-apps -bool true
maybe defaults write com.apple.menuextra.clock ShowSeconds -bool true
maybe defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false

# Configure Finder
maybe defaults write com.apple.finder FXDefaultSearchScope -string SCcf
maybe defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
maybe defaults write com.apple.finder FXPreferredViewStyle -string clmv
maybe defaults write com.apple.finder _FXSortFoldersFirst -bool true
maybe defaults write com.apple.finder _FXSortFoldersFirstOnDesktop -bool true
maybe defaults write com.apple.finder NewWindowTarget -string PfHm
maybe defaults delete com.apple.finder NewWindowTargetPath 2>/dev/null || true
maybe defaults write com.apple.finder ShowPathbar -bool true
maybe defaults write com.apple.finder ShowRecentTags -bool false
maybe defaults write com.apple.finder ShowStatusBar -bool true
maybe defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1 # Sidebar icon size (1 = small, 2 = medium, 3 = large; default: 2)

# Configure input sources
maybe defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
maybe defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
maybe defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
maybe defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false

maybe defaults write com.apple.HIToolbox AppleDictationAutoEnable -int 0 # Disable "Do you want to enable Dictation?" when Control is pressed twice
maybe defaults write com.apple.HIToolbox AppleFnUsageType -int 0         # Press the Fn or Globe key to "Do Nothing"

# Configure keyboard (and Touch Bar)
maybe defaults write NSGlobalDomain AppleKeyboardUIMode -int 2            # Enable keyboard navigation (default: 0)
maybe defaults write NSGlobalDomain com.apple.keyboard.fnState -bool true # Enable "Use F1, F2, etc. keys as standard function keys"
maybe defaults write com.apple.touchbar.agent PresentationModeGlobal -string functionKeys

# Configure trackpad
tap_to_click=1
secondary_click_in_bottom_right_corner=1
disable_force_click=1
for key in com.apple.AppleMultitouchTrackpad com.apple.driver.AppleBluetoothMultitouch.trackpad; do
    if ((tap_to_click)); then
        maybe defaults write $key Clicking -bool true
    fi
    if ((secondary_click_in_bottom_right_corner)); then
        maybe defaults write $key TrackpadCornerSecondaryClick -int 2
        maybe defaults write $key TrackpadRightClick -bool false
    fi
done
if ((tap_to_click)); then
    maybe defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
fi
if ((secondary_click_in_bottom_right_corner)); then
    maybe defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
    maybe defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool false
fi
if ((disable_force_click)); then
    maybe defaults write NSGlobalDomain com.apple.trackpad.forceClick -bool false
    maybe defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -int 0 # Default: 1
    maybe defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true
    maybe defaults -currentHost write com.apple.trackpad.threeFingerTapGesture -int 2 # Default: 0
    for key in com.apple.AppleMultitouchTrackpad com.apple.driver.AppleBluetoothMultitouch.trackpad; do
        maybe defaults write $key TrackpadThreeFingerTapGesture -int 2 # Default: 0
    done
fi

# Uncomment to enable or disable activateSettings output as needed:
#maybe defaults write com.apple.activatesettings log -bool true
#maybe defaults delete com.apple.activatesettings log
maybe /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u

maybe killall Dock
maybe killall Finder
