#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

maybe update-desktop-database ~/.local/share/applications

# Stop updates triggering `/usr/bin/udevadm trigger -c change`
replace_file --sudo /etc/systemd/do-not-udevadm-trigger-on-update </dev/null

if [[ -d ~lightdm ]] && ! sudo test ~lightdm/.config/autorandr -ef ~/.config/autorandr; then
    maybe sudo -u lightdm install -d -m 00700 -v ~lightdm/.config
    maybe sudo -u lightdm ln -sfTv ~/.config/autorandr ~lightdm/.config/autorandr
fi

if [[ -f ~/.face ]]; then
    # Make directories between ~ and ~/.face executable
    parent=$(realpath ~)
    child=$(realpath ~/.face)
    child=${child%/*}

    args=()
    i=0
    while true; do
        args[i++]=$child
        [[ ! $child -ef $parent ]] ||
            break
        # If ~/.face is outside ~, update ~ and ~/.face permissions, otherwise
        # update every directory in the hierarchy from ~/.face to ~
        [[ ${child#$parent} != "$child" ]] || {
            args[i++]=$parent
            break
        }
        child=${child%/*}
    done

    maybe chmod -c a+x "${args[@]}"
fi
