#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

shopt -s extglob nullglob

mimeinfo=({~/.local,/usr/local,/usr}/share/applications/mimeinfo.cache!(?))

# Format: <app>[+(<app_to_override>|<mime_type>)...]
default_apps=(
    # Assign types opened by Geany and Vim to VS Code
    code+geany+vim
    # Prefer Firefox for `text/html`
    firefox
    # Prefer Thunderbird for `x-scheme-handler/mailto`
    org.mozilla.Thunderbird
    # Prefer Thunar for `inode/directory`
    thunar
    org.nomacs.ImageLounge
    org.xfce.ristretto
    typora
    org.gnome.Evince
    vlc
    # Prefer Engrampa Archive Manager for `application/x-cd-image` and other
    # types also opened by gnome-disk-image-mounter or VLC
    engrampa+application/vnd.microsoft.portable-executable
)

# Split a <default_apps> entry into variables `first`, `types`, `apps`, adding
# ".desktop" to `first` and entries in `apps`
function split_default_app() {
    local IFS=+ parts
    read -ra parts <<<"$1"
    set -- "${parts[@]}"
    first=$1.desktop
    shift
    types=()
    apps=()
    while (($#)); do
        if [[ $1 == */* ]]; then
            types[${#types[@]}]=$1
        else
            apps[${#apps[@]}]=$1.desktop
        fi
        shift
    done
}

function app_handles() {
    awk -F= -vapp=";$1;" 'index(";" $2 ";", app) { print $1 }' "${mimeinfo[@]}"
}

maybe update-desktop-database ~/.local/share/applications

replace_file ~/.config/mimeapps.list < <(
    for entry in "${default_apps[@]}"; do
        split_default_app "$entry"
        {
            [[ -z ${types+1} ]] || printf '%s\n' "${types[@]}"
            for app in "$first" ${apps+"${apps[@]}"}; do
                app_handles "$app"
            done
        } | awk -vapp="$first" '{ print $0 "=" app }'
    done | awk -F= '
BEGIN { print "[Default Applications]" }
      { m[$1] = $2 }
END   { for (t in m) { print t "=" m[t] | "sort" } close("sort") }'
    printf '\n[%s]\n' "Added Associations"
    for entry in "${default_apps[@]}"; do
        split_default_app "$entry"
        [[ -n ${apps+1} ]] || continue
        for app in "${apps[@]}"; do
            app_handles "$app"
        done | grep -Fxvf <(app_handles "$first") |
            awk -vapp="$first" '{ print $0 "=" app ";" }'
    done | sort -u
)

# Stop updates triggering `/usr/bin/udevadm trigger -c change`
replace_file --sudo /etc/systemd/do-not-udevadm-trigger-on-update </dev/null

if [[ -d ~lightdm ]] && ! sudo test ~lightdm/.config/autorandr -ef ~/.config/autorandr; then
    maybe sudo -u lightdm install -d -m 00700 -v ~lightdm/.config
    maybe sudo -u lightdm ln -sfTv ~/.config/autorandr ~lightdm/.config/autorandr
fi

if [[ -f ~/.face ]]; then
    # Make directories between ~ and ~/.face executable
    parent=$(realpath ~)
    child=$(realpath ~/.face)
    child=${child%/*}

    args=()
    i=0
    while true; do
        args[i++]=$child
        [[ ! $child -ef $parent ]] ||
            break
        # If ~/.face is outside ~, update ~ and ~/.face permissions, otherwise
        # update every directory in the hierarchy from ~/.face to ~
        [[ ${child#$parent} != "$child" ]] || {
            args[i++]=$parent
            break
        }
        child=${child%/*}
    done

    maybe chmod -c a+x "${args[@]}"
fi
