#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
macos)
    file=~/Library/Containers/fr.handbrake.HandBrake/Data/Library/Application\ Support/HandBrake/UserPresets.json
    file2=$df_root/by-platform/linux/HandBrake/files/presets.json
    if [[ -f $file ]] && [[ -f $file2 ]] && [[ ! $file -ef $file2 ]]; then
        replace_file "$file2" <"$file"
    fi
    ;;
esac

with_each files/presets.json \
    replace_file '{}' jq_safe --indent 4 '.PresetList[].ChildrenArray |= sort_by(.PresetName | split("(?<![0-9.])(?=[0-9.])|(?<=[0-9.])(?![0-9.])"; null) | map(. as $part | try tonumber catch $part))'
