#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' ~/.config
    ;;
macos)
    printf '%s\n' ~/"Library/Application Support"
    ;;
*)
    exit 3
    ;;
esac
