#!/bin/sh

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' ~/.config
    ;;
macos)
    printf '%s\n' ~/"Library/Application Support"
    ;;
windows)
    dir=$(path_get AppData)
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
