#!/bin/bash

# Prevents private/<name> being pushed to remotes other than *-<name>.git

remote_name=$1
remote_url=$2

while read -r local_ref local_sha remote_ref remote_sha; do
    # Remote branch delete
    if [[ $local_sha =~ ^0+$ ]]; then
        continue
    fi

    # New remote branch
    if [[ $remote_sha =~ ^0+$ ]] && [[ $local_ref =~ ^refs/heads/private/(.*) ]]; then
        if [[ $remote_url == *-${BASH_REMATCH[1]}.git ]]; then
            echo "Allowing push from private branch '${local_ref#refs/heads/}' to private repo '$remote_url'" >&2
            continue
        fi
        echo "Rejecting push from private branch '${local_ref#refs/heads/}' to unrecognised repo '$remote_url'" >&2
        exit 1
    fi
done
