#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

function normalise_data_sources() {
    jq_safe --sort-keys |
        jq --indent 4 '.connections |= (to_entries | sort_by(.value.folder, .value.name) | from_entries)'
}

with_each files/workspace6/General/.dbeaver/data-sources.json \
    replace_file '{}' normalise_data_sources

file=$(find_first files/workspace6/General/.dbeaver/credentials-config.json) || exit 2
replace=${file%files/workspace6/General/.dbeaver/credentials-config.json}credentials-config.json

replace_file "$replace" < <(
    # Decrypt
    openssl aes-128-cbc -d -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 -in "$file" |
        # Skip 16-byte preamble
        dd bs=16 skip=1 status=none |
        # Fix escapes
        sed -E 's/([^\])(\\[^\\"])/\1\\\2/g' |
        # Sort and print
        jq 'to_entries | sort_by(.key) | from_entries'
)
