#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

file=files/workspace6/General/.dbeaver/credentials-config.json
file=$(find_first "$file") || exit 2

replace_file "${file%.json}.clean.json" < <(
    # Decrypt
    openssl aes-128-cbc -d -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 -in "$file" |
        # Skip 16-byte preamble
        dd bs=16 skip=1 status=none |
        # Fix escapes
        sed -E 's/([^\])(\\[^\\"])/\1\\\2/g' |
        # Sort and print
        jq 'to_entries | sort_by(.key) | from_entries'
)
