#!/bin/sh

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' ~/.local/share/DBeaverData
    ;;
macos)
    printf '%s\n' ~/Library/DBeaverData
    ;;
windows)
    dir=$(path_get AppData)/DBeaverData
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
