#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' "${XDG_CONFIG_HOME:-$HOME/.config}/composer"
    ;;
macos)
    printf '%s\n' ~/.composer
    ;;
windows)
    dir=$(path_get AppData)/Composer
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
