#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

plist=~/Library/Preferences/com.hegenberg.BetterSnapTool.plist

file=$(find_first com.hegenberg.BetterSnapTool.plist) || exit 3

plist_import "" "$file"
