#!/bin/sh

case "$df_platform" in
linux)
    printf '%s\n' ~/.config/keepassxc
    ;;
macos)
    printf '%s\n' ~/"Library/Application Support/KeePassXC"
    ;;
windows)
    dir=$(path_get AppData)/KeePassXC/keepassxc.ini
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
