#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' ~/.config/keepassxc
    ;;
macos)
    printf '%s\n' ~/"Library/Application Support/KeePassXC"
    ;;
windows)
    dir=$(path_get AppData)/KeePassXC
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
