#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' ~/.config/Nextcloud
    ;;
macos)
    if [[ -e ~/Library/Containers/com.nextcloud.desktopclient ]]; then
        printf '%s\n' ~/Library/Containers/com.nextcloud.desktopclient/Data/Library/Preferences/Nextcloud
    else
        printf '%s\n' ~/Library/Preferences/Nextcloud
    fi
    ;;
windows)
    dir=$(path_get AppData)/Nextcloud
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
