#!/bin/sh

. "$df_root/bin/lib/bash-helpers.sh" || exit

case "$df_platform" in
linux)
    printf '%s\n' ~/.config/Nextcloud
    ;;
macos)
    printf '%s\n' ~/Library/Preferences/Nextcloud
    ;;
windows)
    dir=$(path_get AppData)/Nextcloud
    printf '%s\n' "$dir"
    ;;
*)
    exit 3
    ;;
esac
