#!/usr/bin/env bash

. "$df_root/bin/lib/bash-helpers.sh" || exit

type -P code >/dev/null || exit 0

if code=$(find_first code); then
    link_file "$code" ~/.local/bin/code
fi

if php=$(find_first php-xdebug); then
    link_file "$php" ~/.local/bin/php-xdebug
fi

if php=$(find_first php74-xdebug); then
    link_file "$php" ~/.local/bin/php74-xdebug
fi

if [[ $df_platform == macos ]]; then
    shopt -s nullglob
    versions=({/usr/local,/opt/homebrew}/opt/php@*)
    for version in ${versions+"${versions[@]}"}; do
        [[ -x $version/bin/php ]] || continue
        ver=${version#*/php@}
        ver=${ver//./}
        link_file "$version/bin/php" ~/".local/bin/php$ver"
    done
fi

extensions=$(mktemp)
install=$(mktemp)
installed=$(mktemp)
with_each extensions.txt \
    cat '{}' | sed -E 's/[[:blank:]]*(#.*)?//g; /^$/d' | sort -u | tee "$extensions" >"$install"

while true; do
    code --list-extensions | sort -u >"$installed"
    extension=$(comm -23 "$install" "$installed" | head -n1)
    [[ -n ${extension:+1} ]] || break
    maybe code --install-extension "$extension"
    grep -Fxv "$extension" "$install" >"$installed" || true
    cp "$installed" "$install"
done

IFS=$'\n'
unknown=($(comm -13 "$extensions" "$installed"))
if [[ -n ${unknown+1} ]]; then
    echo "${#unknown[@]} unknown extension(s):"
    printf '%s\n' "${unknown[@]}"
fi
