#!/bin/sh

CODE=$(
    # Remove the script's directory, as specified, without following any
    # symlinks, from PATH to prevent infinite recursion
    DIR=${0%/*}
    [ "$DIR" != "$0" ] || DIR=$PWD
    PATH=$(printf '%s:' "$PATH" |
        awk -vRS='/*:' -vd="$DIR" '
$0 == d { next } l++ { printf(":") } { printf("%s", $0) } END { print }') &&
        command -v code
) || {
    echo "code not found" >&2
    exit 1
}
FIFO=/tmp/code.fifo.stderr.$$
# $FIFO may already exist, e.g. if the script is called multiple times from an
# interactive shell
[ -p "$FIFO" ] || mkfifo "$FIFO" || exit
sed "/^\\[lua\\]: Couldn't find message for key /d" <"$FIFO" >&2 &
exec "$CODE" "$@" 2>"$FIFO"
